### PR TITLE
add an inViewportContainer prop

### LINKED ISSUE #14: Binding to a different container
With vuewport Mixinx is possibile to bind a different container that not is the BODY?
Becouse i have a container that scroll but is not the body of the page

### PR DESCRIPTION
**Pull request by Eh2406**
closes #14

I am new to Coffeescript, Vue mixins , Yarn... so I may have done this wrong.
How does this look?

### CODE REVIEW

**Comment by Eh2406** [comment]
I don't think the CI errores are related to this PR.

**Comment by Vaulverin** [comment]
@weotch, merge this pull request please :)

**Comment by weotch** [comment]
Yeah, agreed that the failed tests are unrelated

**Comment by weotch** [comment]
Released as 1.1.0.  Thanks @Eh2406

**Pull request merged**
